FROM docker-registry.cdweb.biz/dotnet/dotnet-dev:6.0 AS img

WORKDIR /src
COPY . .
RUN dotnet publish src/Api/AuthenticationAPI.Api.csproj -c Debug -o /app

WORKDIR /app
ENV ASPNETCORE_URLS http://*:5080;http://*:5081;http://*:5443
ENV ASPNETCORE_HTTP_PORT=5080
ENV MANAGEMENT_HTTP_PORT=5081
EXPOSE 5080 5081 5443
ENTRYPOINT ["dotnet", "AuthenticationAPI.Api.dll"]
